inventory_system/inventory_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include(('user.urls', 'user'), namespace='user')),
    path('trabajadores/', include(('trabajadores.urls', 'trabajadores'), namespace='trabajadores')),
    path('productos/', include(('productos.urls', 'productos'), namespace='productos')),
    path('prestamos/', include(('prestamos1.urls', 'prestamos1'), namespace='prestamos')),
    path('devoluciones/', include(('devoluciones.urls', 'devoluciones'), namespace='devoluciones')),
    path('admin/', admin.site.urls),
]

# permite mostrar las imagenes en el template
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory_system/prestamos1/urls.py
from django.urls import path
from .reportes import imprimir_prestamo, imprimir_prestamo_total
from .views import PrestamoView, PrestamoNew



urlpatterns = [
    path('prestamo', PrestamoView.as_view(), name='prestamo_list'),
    path('prestamo/new', PrestamoNew.as_view(), name='prestamo_new'),

    path('prestamo/<int:prestamo_id>/imprimir', imprimir_prestamo, name='prestamo_imprimir_uno'),
    path('prestamo/reporte', imprimir_prestamo_total, name='prestamo_reporte'),
   
]

inventory_system/user/urls.py
from django.urls import path
from django.urls import include
from .views import Home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',Home.as_view(), name='home'),
    path('login',auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout',auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
]

inventory_system/prestamos1/models.py
from django.db import models
from trabajadores.models import Trabajador
from productos.models import Producto
from user.models import ClaseModelo
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.utils.text import slugify
import uuid
# Create your models here. 



class Prestamo(ClaseModelo):
    prestamo_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    fechaPrestamo = models.DateTimeField(auto_now_add=True)
    trabajador = models.ForeignKey(Trabajador, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    ''' slug = models.SlugField(null=False, blank=False, unique=True) '''
    observacion = models.CharField(max_length=100)

    def __str__(self):
        return '{}:{}:{}'.format(self.trabajador,self.producto,self.prestamo_id)

    class Meta:
        verbose_name_plural = 'Prestamos'

def set_prestamo_id(sender, instance, *args, **kwargs):
    if not instance.prestamo_id:
        instance.prestamo_id = str(uuid.uuid4())[:8]

pre_save.connect(set_prestamo_id, sender=Prestamo)


@receiver(post_save, sender=Prestamo)
def actualizar_producto(sender, instance, **kwargs):
    
    id_producto = instance.producto.id
    

    pro = Producto.objects.filter(pk=id_producto).first()

    if pro:
        pro.estado_prestamo=False
        pro.save()

inventory_system/prestamos1/forms.py
from django import forms
from .models import Prestamo
from productos.models import Producto
from trabajadores.models import Trabajador

class PrestamoForm(forms.ModelForm):
    # mostrar solo las categorias activas o True
    trabajador = forms.ModelChoiceField(
        queryset = Trabajador.objects.filter(estado=True)
        .order_by('id')

    )
    producto = forms.ModelChoiceField(
        queryset = Producto.objects.filter(estado=True, estado_prestamo=True)
        .order_by('id')

    )
    class Meta:
        model = Prestamo
        fields = ['trabajador','producto', 'observacion']
        exclude = ['prestamo_id']
        labels = {'trabajador': 'Trabajador', 'producto': 'Producto', 'observacion': 'Observacion'}
        widget = {'observacion': forms.TextInput}

    # sobreeescribir el init para poder agregar clases de botstrap a los inputs
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # iteramos todos los campos
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

        self.fields['trabajador'].empty_label = 'Seleccione Empleado'
        self.fields['producto'].empty_label = 'Seleccione Producto'

inventory_system/prestamos1/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .models import Prestamo
from .forms import PrestamoForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin


class PrestamoView(LoginRequiredMixin, generic.ListView):
    model = Prestamo
    template_name = 'prestamos/prestamo_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'


class PrestamoNew(SuccessMessageMixin, LoginRequiredMixin, generic.CreateView):
    model = Prestamo
    template_name = 'prestamos/prestamo_form.html'
    context_object_name = 'obj'
    form_class = PrestamoForm
    success_url = reverse_lazy('prestamos:prestamo_list')  
    login_url = 'bases:login'
    success_message = 'Registro de Prestamo Creado con Exito'

    # para tomar el id del user y se guarda en el campo uc
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

inventory_system/prestamos1/templates/prestamos/prestamo_all.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reporte de Prestamos </title>
    
    <style type="text/css">
    @page{
        size:letter;
        margin:1cm;
    }

    .table td .numero{
        text-align: center;
    }

    table{
        border: black 1px solid;
        text-align: center;
        border-collapse: collapse;
        width: 100%;
    }

    th {
   background: #eee;
}
td, th{
    padding: 2px 2px;
    padding-left: 1px;
    padding-right: 1px;
}
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <center>
                <h4 class="text-center">Sistema de inventario MARSED S.A.</h4>
            </center>
                <h3>Reporte de prestamos al: {{ today|date:"d/m/Y" }}</h3>
            </div>
            <hr>
            <table class="table">
                <thead >
                    <th>Id</th>
                    <th>Responsable prestamo</th>
                    <th>Empleado</th>
                    <th>Producto</th>
                    <th>Observacion</th>
                    <th>Fecha Prestamo</th>
                    <th>Estado</th>
                </thead>

                <tbody>
                    {% for item in obj %}
                        <tr>
                            <td class="numero">{{item.prestamo_id}}</td>
                            <td class="numero">{{item.uc}}</td>
                            <td class="numero">{{item.trabajador}}</td>
                            <td class="numero">{{item.producto}}</td>
                            <td class="numero">{{item.observacion}}</td>
                            <td class="numero">{{item.fechaPrestamo}}</td>
                            <td class="numero">{{item.estado|yesno:"Activo, Inactivo"}}</td>
                            
                        
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

inventory_system/prestamos1/templates/prestamos/prestamo_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form  method="POST" class="form-inline" enctype="multipart/form-data">
    {% csrf_token %}
<div class="col-xl-12 col-md-12 mb-12">
  {% if obj %}
    <div class="card border-left-warning shadow h-100 py-2">
      {% else %}
      <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
              {% if obj %}
              Editar Prestamo
              {% else %}
              Nuevo Prestamo
              {% endif %}
              
            </div>
            <div class="dropdown-divider"></div>
            <div class="row p-2">
                
                    {{form.as_p}}
                
            </div>
           
            <div class="dropdown-divider"></div>
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-danger"><span class="fa fa-save">Guardar</span></button>
                    <a href="{% url 'prestamos:prestamo_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                </div>
            </div>
            
          </div>
          
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block js_page %}

{% endblock %}

inventory_system/prestamos1/templates/prestamos/prestamo_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Lista de Prestamos</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>Acciones
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'prestamos:prestamo_new' %}"><i class="far fa-calendar-plus"></i> Nuevo Prestamo</a>
          <a class="dropdown-item" href="{% url 'prestamos:prestamo_reporte' %}" target="reportes"><i class="fas fa-print"></i> Reporte</a>
          
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        <!-- Controlo si no hay categorias con un mensaje -->
      {% if not obj %} 
      <div class="alert alert-info">
        No Hay Prestamos
      </div> 
      {% else  %} 
      <table class="table table-striped table-hover">
          <thead>
            <th>Id</th>
            <th>Responsable</th>
            <th>Empleado</th>
          <th>Producto</th>
          <th>Observacion</th>
          <th>Fecha Prestamo</th>
          <th>Estado</th>
          <th class="all">Accion</th>
        </thead>
        <tbody>
            {% for item in obj %}
                <tr>
                    <td>{{item.prestamo_id}}</td>
                    <td>{{item.uc}}</td>
                    <td>{{item.trabajador}}</td>
                    <td>{{item.producto}}</td>
                    <td>{{item.observacion}}</td>
                    <td>{{item.fechaPrestamo}}</td>
                    <td>{{item.estado|yesno:"Activo, Inactivo"}}</td>
                    <td>
                        <a href="#" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                        
                        <a href="{% url 'prestamos:prestamo_imprimir_uno' item.id %}" class="btn btn-success btn-circle" role="button" target="reportes"><i class="fas fa-print"></i></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
      {% endif  %} 

    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  //llamada al plugin de jquerys
  $(document).ready(function(){
    $('.table').DataTable()
  })
</script>
{% endblock %}

inventory_system/prestamos1/templates/prestamos/prestamo_uno.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prestamo Equipos</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style type="text/css">
    @page{
        size:letter;
        margin:1cm;
    }

    .table td .numero{
        text-align: center;
    }

    .table{
        border: black 1px solid;
        text-align: center;
    }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <center>
                <h4 class="text-center">Sistema de inventario MARSED S.A.</h4>
            </center>
                <h3>Ficha de prestamo al: {{ today|date:"d/m/Y" }}</h3>
            </div>
            <hr>
            <table class="table">
                <thead class="thead-dark">
                    <th>Id</th>
                    <th>Responsable prestamo</th>
                    <th>Empleado</th>
                    <th>Producto</th>
                    <th>Observacion</th>
                    <th>Fecha Prestamo</th>
                    <th>Estado</th>
                </thead>

                <tbody>
                    
                        <tr>
                            <td class="numero">{{prestamo.prestamo_id}}</td>
                            <td class="numero">{{prestamo.uc}}</td>
                            <td class="numero">{{prestamo.trabajador}}</td>
                            <td class="numero">{{prestamo.producto}}</td>
                            <td class="numero">{{prestamo.observacion}}</td>
                            <td class="numero">{{prestamo.fechaPrestamo}}</td>
                            <td class="numero">{{prestamo.estado|yesno:"Activo, Inactivo"}}</td>
                            
                        </tr>
                    
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>