inventory_system/inventory_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include(('user.urls', 'user'), namespace='user')),
    path('trabajadores/', include(('trabajadores.urls', 'trabajadores'), namespace='trabajadores')),
    path('productos/', include(('productos.urls', 'productos'), namespace='productos')),
    path('prestamos/', include(('prestamos1.urls', 'prestamos1'), namespace='prestamos')),
    path('devoluciones/', include(('devoluciones.urls', 'devoluciones'), namespace='devoluciones')),
    path('admin/', admin.site.urls),
]

# permite mostrar las imagenes en el template
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory_system/productos/urls.py
from django.urls import path
from .views import CategoriaEdit, CategoriaNew, CategoriaView, categoria_inactivar, MarcaEdit, MarcaNew, MarcaView, marca_inactivar,  ProductoView, ProductoNew, ProductoEdit, producto_inactivar
from .reportes import imprimir_producto_total
#from .views import 

urlpatterns = [
    path('categoria', CategoriaView.as_view(), name='categoria_list'),
    path('categoria/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categoria/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categoria/inactivar/<int:id>', categoria_inactivar, name='categoria_inactivar'),

    path('marca', MarcaView.as_view(), name='marca_list'),
    path('marca/new', MarcaNew.as_view(), name='marca_new'),
    path('marca/edit/<int:pk>', MarcaEdit.as_view(), name='marca_edit'),
    path('marca/inactivar/<int:id>', marca_inactivar, name='marca_inactivar'),


    path('productos', ProductoView.as_view(), name='producto_list'),
    path('productos/new', ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path('productos/inactivar/<int:id>', producto_inactivar, name='producto_inactivar'),

    path('productos/reporte', imprimir_producto_total, name='producto_reporte'),

]

inventory_system/user/urls.py
from django.urls import path
from django.urls import include
from .views import Home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',Home.as_view(), name='home'),
    path('login',auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout',auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
]

inventory_system/productos/models.py
from django.db import models
from user.models import ClaseModelo

# Create your models here.

class Categoria(ClaseModelo):
    descripcion = models.CharField(max_length=50, unique=True)


    # sobreecribo para tomar el valor de descripcion
    def __str__(self):
        return '{}'.format(self.descripcion)

    # sobreescribo este metodo para guardar en mayusculas la descripcion
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

class Marca(ClaseModelo):
    descripcion = models.CharField(max_length=50, unique=True)


    # sobreecribo para tomar el valor de descripcion
    def __str__(self):
        return '{}'.format(self.descripcion)

    # sobreescribo este metodo para guardar en mayusculas la descripcion
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save()

class Producto(ClaseModelo):
    descripcion = models.CharField(max_length=50)
    modelo = models.CharField(max_length=50)
    estado_prestamo = models.BooleanField(default=True)
    
    categoria = models.ForeignKey(Categoria, null=True, blank=True, on_delete=models.CASCADE)
    marca = models.ForeignKey(Marca, null=True, blank=True, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='producto/', null=True, blank=True)

    # sobreecribo para tomar el valor de descripcion
    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion, self.marca.descripcion) 

    # sobreescribo este metodo para guardar en mayusculas la descripcion
    def save(self):
        self.descripcion = self.descripcion.upper()
        self.modelo = self.modelo.upper()
        super(Producto, self).save()

inventory_system/user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fechaCreacion = models.DateTimeField(auto_now_add=True)
    fechaModificacion = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        abstract = True

inventory_system/productos/forms.py
from django import forms

from .models import Categoria, Producto, Marca


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['descripcion', 'estado']
        labels = {'descripcion': 'Descripcion de la Categoria', 'estado': 'Estado'}
        widget = {'descripcion': forms.TextInput}

    # sobreeescribir el init para poder agregar clases de botstrap a los inputs
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # iteramos todos los campos
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


""" marca form """
class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ['descripcion', 'estado']
        labels = {'descripcion': 'Descripcion de la Marca', 'estado': 'Estado'}
        widget = {'descripcion': forms.TextInput}

    # sobreeescribir el init para poder agregar clases de botstrap a los inputs
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # iteramos todos los campos
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

""" producto form """
class ProductoForm(forms.ModelForm):

    categoria = forms.ModelChoiceField(
        queryset = Categoria.objects.filter(estado=True)
        .order_by('descripcion')

    )
    marca = forms.ModelChoiceField(
        queryset = Marca.objects.filter(estado=True)
        .order_by('descripcion')

    )
    class Meta:
        model = Producto
        fields = ['descripcion', 'marca', 'modelo', 'estado', 'categoria', 'imagen']
        labels = {'descripcion':'Descripcion Producto', 'marca':'Marca', 'modelo':'Modelo', 'estado': 'Estado', 'categoria': 'Categoria'}
        widget = {'descripcion': forms.TextInput, 'modelo': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # iteramos todos los campos
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control p-2'
            })
        

        self.fields['categoria'].empty_label = 'Seleccione categoria'
        self.fields['marca'].empty_label = 'Seleccione marca'

inventory_system/productos/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .models import Categoria, Producto, Marca
from .forms import CategoriaForm, ProductoForm, MarcaForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
# Create your views here.


class CategoriaView(LoginRequiredMixin, generic.ListView ):
    model = Categoria
    template_name = 'productos/categoria_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'

# este CreateView dice que es un form que ingresa datos
class CategoriaNew(SuccessMessageMixin, LoginRequiredMixin, generic.CreateView):
    model = Categoria
    template_name = 'productos/categoria_form.html'
    context_object_name = 'obj'
    form_class = CategoriaForm
    success_url = reverse_lazy('productos:categoria_list')  
    login_url = 'bases:login'
    success_message = 'Categoria Creado con Exito'

    # para tomar el id del user y se guarda en el campo uc
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class CategoriaEdit(SuccessMessageMixin, LoginRequiredMixin, generic.UpdateView):
    model = Categoria
    template_name = 'productos/categoria_form.html'
    context_object_name = 'obj'
    form_class = CategoriaForm
    success_url = reverse_lazy('productos:categoria_list')  
    login_url = 'bases:login'
    success_message = 'Categoria Modificada'


def categoria_inactivar(request, id):
    # consulta a la bd para obtener el id
    cat = Categoria.objects.filter(pk=id).first()
    contexto = {}
    template_name = 'productos/producto_inactivar.html'
    
    if not cat:
        return redirect('productos:categoria_list')
    
    if request.method =='GET':
        contexto = {'obj':cat}
    
    # cambio el estado de la marca y lo guardo en la bd
    if request.method =='POST':
        cat.estado=False
        cat.save()
        messages.success(request, 'Categoria INACTIVADA')
        return redirect('productos:categoria_list')
    return render(request, template_name, contexto)


""" Marca Views """

class MarcaView(LoginRequiredMixin, generic.ListView ):
    model = Marca
    template_name = 'productos/marca_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'

# este CreateView dice que es un form que ingresa datos
class MarcaNew(SuccessMessageMixin, LoginRequiredMixin, generic.CreateView):
    model = Marca
    template_name = 'productos/marca_form.html'
    context_object_name = 'obj'
    form_class = MarcaForm
    success_url = reverse_lazy('productos:marca_list')  
    login_url = 'bases:login'
    success_message = 'Marca Creada con exito'

    # para tomar el id del user y se guarda en el campo uc
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class MarcaEdit(SuccessMessageMixin, LoginRequiredMixin, generic.UpdateView):
    model = Marca
    template_name = 'productos/marca_form.html'
    context_object_name = 'obj'
    form_class = MarcaForm
    success_url = reverse_lazy('productos:marca_list')  
    login_url = 'bases:login'
    success_message = 'Marca Modificada'


def marca_inactivar(request, id):
    # consulta a la bd para obtener el id
    marca = Marca.objects.filter(pk=id).first()
    contexto = {}
    template_name = 'productos/producto_inactivar.html'
    
    if not marca:
        return redirect('productos:marca_list')
    
    if request.method =='GET':
        contexto = {'obj':marca}
    
    # cambio el estado de la marca y lo guardo en la bd
    if request.method =='POST':
        marca.estado=False
        marca.save()
        messages.success(request, 'Marca INACTIVADA')
        return redirect('productos:marca_list')
    return render(request, template_name, contexto)


"""
Producto Views
"""
class ProductoView(LoginRequiredMixin, generic.ListView):
    model = Producto
    template_name = 'productos/producto_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'

class ProductoNew(SuccessMessageMixin, LoginRequiredMixin, generic.CreateView):
    model = Producto
    template_name = 'productos/producto_form.html'
    context_object_name = 'obj'
    form_class = ProductoForm
    success_url = reverse_lazy('productos:producto_list')  
    login_url = 'bases:login'
    success_message = 'Prducto Creado con exito'

    # para tomar el id del user y se guarda en el campo uc
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class ProductoEdit(SuccessMessageMixin, LoginRequiredMixin, generic.UpdateView):
    model = Producto
    template_name = 'productos/producto_form.html'
    context_object_name = 'obj'
    form_class = ProductoForm
    success_url = reverse_lazy('productos:producto_list')  
    login_url = 'bases:login'
    success_message = 'Producto Modificado'


def producto_inactivar(request, id):
    # consulta a la bd para obtener el id
    pro = Producto.objects.filter(pk=id).first()
    contexto = {}
    template_name = 'productos/producto_inactivar.html'
    
    if not pro:
        return redirect('productos:producto_list')
    
    if request.method =='GET':
        contexto = {'obj':pro}
    
    # cambio el estado de la marca y lo guardo en la bd
    if request.method =='POST':
        pro.estado=False
        pro.save()
        messages.success(request, 'Producto INACTIVADO')
        return redirect('productos:producto_list')
    return render(request, template_name, contexto)

inventory_system/productos/templates/productos/categoria_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form  method="POST" class="form-inline">
    {% csrf_token %}
<div class="col-xl-6 col-md-6 mb-6">
  {% if obj %}
    <div class="card border-left-warning shadow h-100 py-2">
      {% else %}
      <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
              {% if obj %}
              Editar
              {% else %}
              Nueva Categoria
              {% endif %}
               
            </div>
            <div class="dropdown-divider"></div>
            <div class="row">
                <div class="col-10">
                    <div class="input-group">
                        <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="descripcion de Categoria" value="{% if obj %} {{obj.descripcion}}{%endif%}">
                    </div>
                    <div class="form-group">
                      <label for="id_estado">Estado</label>
                      <input type="checkbox" name="estado" class="form-control" id="id_estado" {% if obj.estado %} checked {%endif%}>
                  </div>
                </div>
                
            </div>
            <div class="dropdown-divider"></div>
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-danger"><span class="fa fa-save">Guardar</span></button>
                    <a href="{% url 'productos:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                </div>
            </div>
            
          </div>
          
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block js_page %}

{% endblock %}

inventory_system/productos/templates/productos/categoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Lista de Categorias</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'productos:categoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva Categoria</a>
          
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        <!-- Controlo si no hay categorias con un mensaje -->
      {% if not obj %} 
      <div class="alert alert-info">
        No Hay Categorias
      </div> 
      {% else  %} 
      <table class="table table-striped table-hover">
          <thead>
            <th>ID</th>
          <th>Descripcion</th>
          <th>Fecha Creado</th>
          <th>Estado</th>
          <th class="all">Accion</th>
        </thead>
        <tbody>
            {% for item in obj %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.descripcion}}</td>
                    <td>{{item.fechaCreacion|date:"d/m/Y H:m:i"}}</td>
                    <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                    <td>
                        <a href="{% url 'productos:categoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                        <a href="{% url 'productos:categoria_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
      {% endif  %} 

    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  //llamada al plugin de jquerys
  $(document).ready(function(){
    $('.table').DataTable()
  })
</script>
{% endblock %}

inventory_system/productos/templates/productos/marca_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form  method="POST" class="form-inline">
    {% csrf_token %}
<div class="col-xl-6 col-md-6 mb-6">
  {% if obj %}
    <div class="card border-left-warning shadow h-100 py-2">
      {% else %}
      <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
              {% if obj %}
              Editar
              {% else %}
              Nueva Marca
              {% endif %}
               
            </div>
            <div class="dropdown-divider"></div>
            <div class="row">
                <div class="col-10">
                    <div class="input-group">
                        <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="descripcion de Marca" value="{% if obj %} {{obj.descripcion}}{%endif%}">
                    </div>
                    <div class="form-group">
                      <label for="id_estado">Estado</label>
                      <input type="checkbox" name="estado" class="form-control" id="id_estado" {% if obj.estado %} checked {%endif%}>
                  </div>
                </div>
                
            </div>
            <div class="dropdown-divider"></div>
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-danger"><span class="fa fa-save">Guardar</span></button>
                    <a href="{% url 'productos:marca_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                </div>
            </div>
            
          </div>
          
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block js_page %}

{% endblock %}

inventory_system/productos/templates/productos/marca_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Lista de Marcas</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'productos:marca_new' %}"><i class="far fa-calendar-plus"></i> Nueva Marca</a>
          
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        <!-- Controlo si no hay categorias con un mensaje -->
      {% if not obj %} 
      <div class="alert alert-info">
        No Hay Marcas
      </div> 
      {% else  %} 
      <table class="table table-striped table-hover">
          <thead>
            <th>ID</th>
          <th>Descripcion</th>
          <th>Fecha Creado</th>
          <th>Estado</th>
          <th class="all">Accion</th>
        </thead>
        <tbody>
            {% for item in obj %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.descripcion}}</td>
                    <td>{{item.fechaCreacion|date:"d/m/Y H:m:i"}}</td>
                    <td>{{item.estado|yesno:"activo,inactivo"}}</td>
                    <td>
                        <a href="{% url 'productos:marca_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                        <a href="{% url 'productos:marca_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
      {% endif  %} 

    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  //llamada al plugin de jquerys
  $(document).ready(function(){
    $('.table').DataTable()
  })
</script>
{% endblock %}

inventory_system/productos/templates/productos/producto_all.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reporte de Prestamos </title>
    
    <style type="text/css">
    @page{
        size:A4;
        margin:1cm;
    }

    .table td .numero{
        text-align: center;
    }

    table{
        border: black 1px solid;
        text-align: center;
        border-collapse: collapse;
        width: 100%;
    }

    th {
   background: #eee;
}
td, th{
    padding: 2px 2px;
    padding-left: 1px;
    padding-right: 1px;
}
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <center>
                <h4 class="text-center">Sistema de inventario MARSED S.A.</h4>
            </center>
                <h3>Reporte de prestamos al: {{ today|date:"d/m/Y" }}</h3>
            </div>
            <hr>
            <table class="table">
                <thead >
                    <th>Categoria</th>
            <th>Id</th>
            
          <th>Descripcion</th>
          <th>Marca</th>
          <th>Modelo</th>
          <th>Disponibilidad</th>
          <th>Estado</th>
                </thead>

                <tbody>
                    {% for item in obj %}
                        <tr>
                            <td>{{item.categoria}}</td>
                    <td>{{item.id}}</td>
                    
                    <td>{{item.descripcion}}</td>
                    <td>{{item.marca}}</td>
                    <td>{{item.modelo}}</td>
                    <td>{{item.estado_prestamo|yesno:"Disponible, Prestado"}}</td>
                    <td>{{item.estado|yesno:"Activo, Inactivo"}}</td>
                            
                </tr>
                        
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

inventory_system/productos/templates/productos/producto_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form  method="POST" class="form-inline" enctype="multipart/form-data">
    {% csrf_token %}
<div class="col-xl-12 col-md-12 mb-12">
  {% if obj %}
    <div class="card border-left-warning shadow h-100 py-2">
      {% else %}
      <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
              {% if obj %}
              Editar
              {% else %}
              Nuevo Producto
              {% endif %}
              
            </div>
            <div class="dropdown-divider"></div>
            <div class="row p-2">
                
                    {{form.as_p}}
                
                
                <!-- <div class="col-5 p-2">
                    <div class="input-group">
                        {{form.categoria}}
                    </div>
                </div>
                <div class="col-5 p-2">
                    <div class="input-group">
                        {{form.descripcion}}

                    </div>
                </div>
                <div class="col-5 p-2">
                    <div class="form-group">
                        {{form.marca}}
                    </div>
                </div> -->
            </div>
           <!--  <div class="row">
                <div class="col-5 p-2">
                    <div class="input-group">
                        {{form.modelo}}
                    </div>
                </div>
                <div class="col-5 p-2">
                    <div class="input-group">
                        {{form.estado}}

                    </div>
                </div>
                <div class="col-5 p-2">
                    <div class="form-group">
                        {{form.imagen}}
                    </div>
                </div>
                
            </div> -->
            <div class="dropdown-divider"></div>
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-danger"><span class="fa fa-save">Guardar</span></button>
                    <a href="{% url 'productos:producto_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                </div>
            </div>
            
          </div>
          
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block js_page %}

{% endblock %}

inventory_system/productos/templates/productos/producto_inactivar.html
{% extends 'base/base.html' %}

{% block page_content %}
<form  method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1"><i class="fa fa-question-circle"></i> Inactivar a: {{obj.descripcion }} del Sistema?</div>
                <button type="submit" class="btn btn-danger">Si, Inactivar</button>
                <a href="{{request.META.HTTP_REFERER }}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
              </div>
              <div class="col-auto">
                <i class="fa fa-question-circle fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
</form>
{% endblock %}
{% block js_page %}

{% endblock %}

inventory_system/productos/templates/productos/producto_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Lista de Productos</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>Acciones
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'productos:producto_new' %}"><i class="far fa-calendar-plus"></i> Nuevo Producto</a>
          <a class="dropdown-item" href="{% url 'productos:producto_reporte' %}" target="reportes"><i class="fas fa-print"></i> Reporte</a>
          
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        <!-- Controlo si no hay categorias con un mensaje -->
      {% if not obj %} 
      <div class="alert alert-info">
        No Hay Productos
      </div> 
      {% else  %} 
      <table class="table table-striped table-hover">
          <thead>
            <th>Categoria</th>
            <th>Id</th>
            <th>Imagen</th>
          <th>Descripcion</th>
          <th>Marca</th>
          <th>Modelo</th>
          <th>Disponibilidad</th>
          <th>Estado</th>
          <th class="all">Accion</th>
        </thead>
        <tbody>
            {% for item in obj %}
                <tr>
                    <td>{{item.categoria}}</td>
                    <td>{{item.id}}</td>
                    {% if item.imagen %}
                    <td><img src="{{ item.imagen.url }}" width="100" alt="imagn empleado"></td>
                    {%else%}
                    <td><img src="" width="100" alt="imagen producto"></td>
                    {% endif %}
                    <td>{{item.descripcion}}</td>
                    <td>{{item.marca}}</td>
                    <td>{{item.modelo}}</td>
                    <td>{{item.estado_prestamo|yesno:"Disponible, Prestado"}}</td>
                    <td>{{item.estado|yesno:"Activo, Inactivo"}}</td>
                    <td>
                        <a href="{% url 'productos:producto_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                        <a href="{% url 'productos:producto_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
      {% endif  %} 

    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  //llamada al plugin de jquerys
  $(document).ready(function(){
    $('.table').DataTable()
  })
</script>
{% endblock %}