inventory_system/devoluciones/urls.py
from django.urls import path
from .reportes import imprimir_devolucion_total
from .views import DevolucionNew, DevolucionView



urlpatterns = [
    path('devolucion', DevolucionView.as_view(), name='devolucion_list'),
    path('devolucion/new', DevolucionNew.as_view(), name='devolucion_new'),
    path('devolucion/reporte', imprimir_devolucion_total, name='devolucion_reporte'),
    
    
   
]

inventory_system/inventory_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include(('user.urls', 'user'), namespace='user')),
    path('trabajadores/', include(('trabajadores.urls', 'trabajadores'), namespace='trabajadores')),
    path('productos/', include(('productos.urls', 'productos'), namespace='productos')),
    path('prestamos/', include(('prestamos1.urls', 'prestamos1'), namespace='prestamos')),
    path('devoluciones/', include(('devoluciones.urls', 'devoluciones'), namespace='devoluciones')),
    path('admin/', admin.site.urls),
]

# permite mostrar las imagenes en el template
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory_system/prestamos1/urls.py
from django.urls import path
from .reportes import imprimir_prestamo, imprimir_prestamo_total
from .views import PrestamoView, PrestamoNew



urlpatterns = [
    path('prestamo', PrestamoView.as_view(), name='prestamo_list'),
    path('prestamo/new', PrestamoNew.as_view(), name='prestamo_new'),

    path('prestamo/<int:prestamo_id>/imprimir', imprimir_prestamo, name='prestamo_imprimir_uno'),
    path('prestamo/reporte', imprimir_prestamo_total, name='prestamo_reporte'),
   
]

inventory_system/productos/urls.py
from django.urls import path
from .views import CategoriaEdit, CategoriaNew, CategoriaView, categoria_inactivar, MarcaEdit, MarcaNew, MarcaView, marca_inactivar,  ProductoView, ProductoNew, ProductoEdit, producto_inactivar
from .reportes import imprimir_producto_total
#from .views import 

urlpatterns = [
    path('categoria', CategoriaView.as_view(), name='categoria_list'),
    path('categoria/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categoria/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categoria/inactivar/<int:id>', categoria_inactivar, name='categoria_inactivar'),

    path('marca', MarcaView.as_view(), name='marca_list'),
    path('marca/new', MarcaNew.as_view(), name='marca_new'),
    path('marca/edit/<int:pk>', MarcaEdit.as_view(), name='marca_edit'),
    path('marca/inactivar/<int:id>', marca_inactivar, name='marca_inactivar'),


    path('productos', ProductoView.as_view(), name='producto_list'),
    path('productos/new', ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path('productos/inactivar/<int:id>', producto_inactivar, name='producto_inactivar'),

    path('productos/reporte', imprimir_producto_total, name='producto_reporte'),

]

inventory_system/trabajadores/urls.py
from django.urls import path
from .views import TrabajadoView, TrabajadorNew, TrabajadorEdit, trabajador_inactivar
from .reportes import imprimir_trabajador_total
urlpatterns = [
    path('', TrabajadoView.as_view(), name='trabajador_list'),
    path('new', TrabajadorNew.as_view(), name='trabajador_new'),
    path('edit/<int:pk>', TrabajadorEdit.as_view(), name='trabajador_edit'),
    path('inactivar/<int:id>', trabajador_inactivar, name='trabajador_delete'),

    path('trabajadores/reporte', imprimir_trabajador_total, name='trabajador_reporte'),
]

inventory_system/user/urls.py
from django.urls import path
from django.urls import include
from .views import Home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',Home.as_view(), name='home'),
    path('login',auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout',auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
]

inventory_system/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Sistema de Inventario</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'base/vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'base/css/sb-admin-2.min.css'%}" rel="stylesheet">

  <!-- Custom styles for tables -->
  <link href="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.css'%}" rel="stylesheet">

  <!-- jquery confirm -->
  <link href="{% static 'base/vendor/jquery_confirm/jquery-confirm.min.css'%}" rel="stylesheet">

  <!-- favicon -->
  <link  rel="icon"   href="{% static 'image/favicon.PNG' %}" type="image/png" />
</head>

<body id="page-top" class="bg-gradient-primary">

  <!-- Page Wrapper -->
  <div id="wrapper">
    {% block side_bar %}
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'user:home' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-warehouse"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Sistema de Inventario <sup>MARSED</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user:home' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Opciones del Menu
      </div>

      
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-users"></i>
          <span>Trabajador</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Trabajadores de la Empresa</h6>
            {% if perms.trabajadores.view_trabajador %}
            <a class="collapse-item" href="{% url 'trabajadores:trabajador_list' %}">Empleados</a>
            

            <a class="collapse-item" href="{% url 'trabajadores:trabajador_new' %}">Nuevo Empleado</a>
            
            {% endif %}
          </div>
        </div>
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-tools"></i>
          <span>Objetos de Bodega</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Objetos de Bodega:</h6>
            {% if perms.productos.view_producto %}
            <a class="collapse-item" href="{% url 'productos:producto_list' %}">Lista de Productos</a>
            <a class="collapse-item" href="{% url 'productos:producto_new' %}">Nuevo Poducto</a>
            {% endif %}
            {% if perms.productos.view_categoria %}

            <a class="collapse-item" href="{% url 'productos:categoria_list' %}">Categorias</a>
            <a class="collapse-item" href="{% url 'productos:categoria_new' %}">Nueva Categoria</a>
            {% endif %}
            {% if perms.productos.view_marca %}

            <a class="collapse-item" href="{% url 'productos:marca_list' %}">Marcas</a>
            <a class="collapse-item" href="{% url 'productos:marca_new' %}">Nueva Marca</a>
            {% endif %}
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Prestamos/Devoluciones
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item active">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-exchange-alt"></i>
          <span>Prestamos/Devoluciones</span>
        </a>
        <div id="collapsePages" class="collapse show" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Prestamos/Devoluciones:</h6>
            <a class="collapse-item" href="{% url 'prestamos:prestamo_list' %}">Prestamos</a>
            <a class="collapse-item" href="{% url 'devoluciones:devolucion_list' %}">Devoluciones</a>
            
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->
    {% endblock side_bar %}
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">
        {% block top_bar %}
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <div class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            
        </div>
            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.username}}</span>
                <img class="img-profile rounded-circle" src="{% static 'image/usuario.png' %}">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Salir
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->
        {% endblock top_bar %}

        <!-- Begin Page Content -->
        {% block page_content %}
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="text-center">Bienvenidx Sistema de Bodega MARSED</h1>
          <div class="container">
            <div>
              <img src="{% static 'image/logo-1.jpg'%}" alt="img_logo" class="mx-auto d-block" >
            </div>
             
          </div>
         

        </div>
        {% endblock page_content %}
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      {% block footer %}
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Ingenieria de Software 2020</span>
          </div>
        </div>
      </footer>
      {% endblock footer %}
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->
  {% block login %} {% endblock login %}
  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Seguro deseas Salir?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">X</span>
          </button>
        </div>
        <div class="modal-body">Selecciona Salir si estas segurx</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'user:logout' %}">Salir</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'base/vendor/jquery/jquery.min.js'%}"></script>
  <script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'base/vendor/jquery-easing/jquery.easing.min.js'%}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'base/js/sb-admin-2.min.js'%}"></script>
  <!-- tables -->
  <script src="{% static 'base/vendor/datatables/jquery.dataTables.min.js'%}"></script>
  <script src="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.js'%}"></script>
  <!-- jquery confirm js -->
<script src="{% static 'base/vendor/jquery_confirm/jquery-confirm.min.js'%}"></script>
{% block mensajes %}
<script>
  //funcon para mensajes
  function mensaje(msg, color='green'){
      $.alert({
        title:'',
        theme: 'material',
        type: color,
        content: msg
      })
    }

    {% if messages %}
      {% for message in messages %}
          mensaje("{{message}}" )
      {% endfor %}
    {% endif%}
</script>

{% endblock mensajes %}
  {% block js_page %}  {% endblock js_page %}
</body>

</html>