inventory_system/inventory_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include(('user.urls', 'user'), namespace='user')),
    path('trabajadores/', include(('trabajadores.urls', 'trabajadores'), namespace='trabajadores')),
    path('productos/', include(('productos.urls', 'productos'), namespace='productos')),
    path('prestamos/', include(('prestamos1.urls', 'prestamos1'), namespace='prestamos')),
    path('devoluciones/', include(('devoluciones.urls', 'devoluciones'), namespace='devoluciones')),
    path('admin/', admin.site.urls),
]

# permite mostrar las imagenes en el template
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory_system/trabajadores/urls.py
from django.urls import path
from .views import TrabajadoView, TrabajadorNew, TrabajadorEdit, trabajador_inactivar
from .reportes import imprimir_trabajador_total
urlpatterns = [
    path('', TrabajadoView.as_view(), name='trabajador_list'),
    path('new', TrabajadorNew.as_view(), name='trabajador_new'),
    path('edit/<int:pk>', TrabajadorEdit.as_view(), name='trabajador_edit'),
    path('inactivar/<int:id>', trabajador_inactivar, name='trabajador_delete'),

    path('trabajadores/reporte', imprimir_trabajador_total, name='trabajador_reporte'),
]

inventory_system/user/urls.py
from django.urls import path
from django.urls import include
from .views import Home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',Home.as_view(), name='home'),
    path('login',auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout',auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
]

inventory_system/trabajadores/models.py
from django.db import models
from user.models import ClaseModelo

# Create your models here.


class Trabajador(ClaseModelo):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    cedula = models.CharField(max_length=50)
    direccion = models.TextField()
    correo = models.EmailField()
    celular = models.CharField(max_length=10)
    imagen = models.ImageField(upload_to='trabajador/', null=True, blank=True)


    def __str__(self):
        return '{}-{}'.format(self.nombre, self.apellido)


    def save(self):
        self.nombre = self.nombre.upper()
        self.apellido = self.apellido.upper()
        super(Trabajador, self).save()

    class Meta:
        verbose_name_plural = 'Trabajadores'

inventory_system/user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fechaCreacion = models.DateTimeField(auto_now_add=True)
    fechaModificacion = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        abstract = True

inventory_system/trabajadores/forms.py
from django import forms
from .models import Trabajador


class TrabajadorForm(forms.ModelForm):
    class Meta:
        model = Trabajador
        fields = ['nombre', 'apellido', 'cedula', 'direccion', 'correo', 'celular','estado', 'imagen']
        labels = {'nombre': 'Nombre', 'apellido': 'Apellido', 'cedula': 'Cedula', 'direccion': 'Direccion', 'correo': 'Correo', 'celular': 'Celular', 'estado': 'Estado'}

        widget = {'nombre': forms.TextInput, 'apellido': forms.TextInput, 'cedula': forms.NumberInput, 'direccion': forms.TextInput, 'correo': forms.EmailInput, 'celular': forms.NumberInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # iteramos todos los campos
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                    'class': 'form-control'
            })

inventory_system/trabajadores/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .models import Trabajador
from .forms import TrabajadorForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

# Create your views here.

class TrabajadoView(LoginRequiredMixin, generic.ListView):
    model = Trabajador
    template_name = 'trabajadores/trabajador_list.html'
    context_object_name = 'obj'
    login_url = 'user:login'
 

class TrabajadorNew(SuccessMessageMixin, LoginRequiredMixin, generic.CreateView):
    model = Trabajador
    template_name = 'trabajadores/trabajador_form.html'
    context_object_name = 'obj'
    form_class = TrabajadorForm
    success_url = reverse_lazy('trabajadores:trabajador_list')
    login_url = 'user:login'
    success_message = 'Trabajador Creado con Exito'

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


# edit Trabajador 
class TrabajadorEdit(SuccessMessageMixin, LoginRequiredMixin, generic.UpdateView):
    model = Trabajador
    template_name = 'trabajadores/trabajador_form.html'
    context_object_name = 'obj'
    form_class = TrabajadorForm
    success_url = reverse_lazy('trabajadores:trabajador_list')  # cuando se manda el form hay que poner la ruta de donde va despues no puede quedar en la misma ruta
    login_url = 'user:login'
    success_message = 'Trabajador actualizado'


def trabajador_inactivar(request, id):
    # consulta a la bd para obtener el id
    tra = Trabajador.objects.filter(pk=id).first()
    contexto = {}
    template_name = 'trabajadores/trabajador_del.html'
    
    if not tra:
        return redirect('trabajadores:trabajador_list')
    
    if request.method =='GET':
        contexto = {'obj':tra}
    
    # cambio el estado de la marca y lo guardo en la bd
    if request.method =='POST':
        tra.estado=False
        tra.save()
        messages.success(request, 'Trabajador INACTIVADO')
        return redirect('trabajadores:trabajador_list')
    return render(request, template_name, contexto)

inventory_system/trabajadores/templates/trabajadores/trabajador_all.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reporte de Prestamos </title>
    
    <style type="text/css">
    @page{
        size:A4;
        margin:1cm;
    }

    .table td .numero{
        text-align: center;
    }

    table{
        border: black 1px solid;
        text-align: center;
        border-collapse: collapse;
        width: 100%;
    }

    th {
   background: #eee;
}
td, th{
    padding: 2px 2px;
    padding-left: 1px;
    padding-right: 1px;
}

    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <center>
                <h4 class="text-center">Sistema de inventario MARSED S.A.</h4>
            </center>
                <h3>Reporte de Empleados al: {{ today|date:"d/m/Y" }}</h3>
                
            </div>
            <hr>
            <table class="table">
                <thead >
                    <th>ID</th>
           
            
          <th>Nombre y Apellido</th>
          <th>Cedula</th>
          <th>Direccion</th>
          <th>Correo</th>
          <th>Celular</th>
          <th>Estado</th>
                </thead>

                <tbody>
                    {% for item in obj %}
                        <tr>
                            <td>{{item.id}}</td>
                    
                    <td>{{item.nombre }} &nbsp; {{ item.apellido}}</td>
                    <td>{{item.cedula}}</td>
                    <td>{{item.direccion}}</td>
                    <td class="block">{{item.correo}}</td>
                    <td>{{item.celular}}</td>
                    <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                            
                </tr>
                        
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

inventory_system/trabajadores/templates/trabajadores/trabajador_del.html
{% extends 'base/base.html' %}

{% block page_content %}
<form  method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1"><i class="fa fa-question-circle"></i> Inactivar a: {{obj.nombre }} &nbsp; {{ obj.apellido}} del Sistema?</div>
                <button type="submit" class="btn btn-danger">Si, Inactivar</button>
                <a href="{% url 'trabajadores:trabajador_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
              </div>
              <div class="col-auto">
                <i class="fa fa-question-circle fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
</form>
{% endblock %}
{% block js_page %}

{% endblock %}

inventory_system/trabajadores/templates/trabajadores/trabajador_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form  method="POST" class="form-inline" enctype="multipart/form-data">
    {% csrf_token %}
<div class="col-xl-12 col-md-12 mb-12">
  {% if obj %}
    <div class="card border-left-warning shadow h-100 py-2">
      {% else %}
      <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
              {% if obj %}
               <b>Editar</b>
              {% else %}
              <b> Nuevo Trabajador</b>
              {% endif %}
              
            </div>
            <div class="dropdown-divider"></div>
            <div class="row">
                <div class="col-5 p-2" >
                    <div class="input-group">
                        <input type="text" name="nombre" maxlength="100" class="form-control" required id="id_nombre" placeholder="Nombre Empleado" value="{% if obj %} {{obj.nombre}}{%endif%}">
                    </div>
                </div>
                <div class="col-5 p-2">
                    <div class="input-group">
                        <input type="text" name="apellido" maxlength="100" class="form-control" required id="id_apellido" placeholder="Apellido Empleado" value="{% if obj %} {{obj.apellido}}{%endif%}">
                    </div>
                </div>
                <div class="col-5 p-2">
                    <div class="input-group">
                        <input type="text" name="cedula" maxlength="10" class="form-control" required id="id_cedula" placeholder="Cedula" value="{% if obj %} {{obj.cedula}}{%endif%}" onkeypress="return validarNumero(event)" onblur="validar()">
                    </div>
                </div>
                
            </div>
            <div class="row">
                
                <div class="col-10 p-2">
                    <div class="input-group">
                        <input type="text" name="direccion" maxlength="100" class="form-control" required id="id_direccion" placeholder="Direccion Empleado" value="{% if obj %} {{obj.direccion}}{%endif%}">
                    </div>
                </div>
                
            </div>
            <div class="row">
                <div class="col-5 p-2">
                    <div class="input-group">
                        <input type="email" name="correo" maxlength="100" class="form-control" required id="id_correo" placeholder="Correo Empleado" value="{% if obj %} {{obj.correo}}{%endif%}">
                    </div>
                </div>
                <div class="col-5 p-2">
                    <div class="input-group">
                        <input type="text" name="celular" maxlength="10" class="form-control" required id="id_celular" placeholder="Celular Empleado" value="{% if obj %} {{obj.celular}}{%endif%}" onkeypress="return validarNumero(event)" onblur="validar_celular()">
                    </div>
                    <div class="form-group">
                        <label for="id_estado">Estado</label>
                        <input type="checkbox" name="estado" class="form-control" id="id_estado" {% if obj.estado %} checked {%endif%}>
                    </div>
                </div>
                <div class="row">

                    <div class="col-2 p-3">
                        <div class="input-group">
                            
                            <input type="file" name="imagen" accept="image/*"  id="id_imagen">
                        </div>
                    </div>
                    
                </div>
            </div>
            <div class="dropdown-divider"></div>
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-danger"><span class="fa fa-save">Guardar</span></button>
                    <a href="{% url 'trabajadores:trabajador_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                </div>
            </div>
            
          </div>
          
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block js_page %}
<script type="text/javascript" >
    function validarNumero(e) {
        tecla = (document.all) ? e.keyCode : e.which;
        if (tecla == 8)
            return true;
        patron = /[0-9]/;
        te = String.fromCharCode(tecla);
        return patron.test(te);
    }

    function validar() {
        var cedula = document.getElementById("id_cedula").value.trim();
        array = cedula.split("");
        num = array.length;
        if (num == 10) {
            total = 0;
            digito = (array[9] * 1);
            for (i = 0; i < (num - 1); i++) {
                mult = 0;
                if ((i % 2) != 0) {
                    total = total + (array[i] * 1);
                } else {
                    mult = array[i] * 2;
                    if (mult > 9)
                        total = total + (mult - 9);
                    else
                        total = total + mult;
                }
            }
            decena = total / 10;
            decena = Math.floor(decena);
            decena = (decena + 1) * 10;
            final = (decena - total);
            if (((final == 10 && digito == 0) || (final == digito)) && (cedula != '0000000000' && cedula != '2222222222' && cedula != '4444444444' && cedula != '5555555555' && cedula != '7777777777' && cedula != '9999999999')) {
                //       document.getElementById("salida").innerHTML = ("Cedula Válida")
                return true;
            } else {
                //      document.getElementById("salida").innerHTML = ("Cedula no es valida")
                //                alert("Cedula no es valida")
                alert( "Cédula no valida");

                document.getElementById('id_cedula').value = "";

                return false;
            }
        } else {
            //            alert("Cedula tiene menos de 10 digitos")
            alert("La Cédula debe tener 10 dígitos");
            document.getElementById('id_cedula').value = "";

            return false;
        }
    }

    function validar_celular() {
            var celular = document.getElementById("id_celular").value
                if (celular) {
                    if (celular.length < 10) {
                       
                        alert("faltan números")
                        document.getElementById('id_celular').value = "";

                    }
                }

                var expresion = /^09[\d]{8}$/;
                //var expresion = /^( 09)+(0-9)+/
                if (!expresion.test(celular)) {
                    
                    alert("Número NO valido");
                    document.getElementById('id_celular').value = "";
                   

                } else {
                    return true;

                }
            }
</script>
{% endblock %}

inventory_system/trabajadores/templates/trabajadores/trabajador_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Lista de Empleados</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'trabajadores:trabajador_new'%}"><i class="far fa-calendar-plus"></i> Nuevo Empleado</a>
          <a class="dropdown-item" href="{% url 'trabajadores:trabajador_reporte' %}" target="reportes"><i class="fas fa-print"></i> Reporte</a>
          
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        <!-- Controlo si no hay categorias con un mensaje -->
      {% if not obj %} 
      <div class="alert alert-info">
        No Hay Trabajadores
      </div> 
      {% else  %} 
      <table class="table table-striped table-hover">
          <thead>
            <th>ID</th>
            <th>Foto</th>
            
          <th>Nombre y Apellido</th>
          <th>Cedula</th>
          <th>Direccion</th>
          <th>Correo</th>
          <th>Celular</th>
          <th>Estado</th>
          <th class="all">Accion</th>
        </thead>
        <tbody>
            {% for item in obj %}
                <tr>
                    <td>{{item.id}}</td>
                    {% if item.imagen %}
                    <td><img src="{{ item.imagen.url }}" width="100" alt="imagn empleado"></td>
                    {%else%}
                    <td><img src="" width="100" alt="imagn empleado"></td>
                    {% endif %}
                    <td>{{item.nombre }} &nbsp; {{ item.apellido}}</td>
                    <td>{{item.cedula}}</td>
                    <td>{{item.direccion}}</td>
                    <td>{{item.correo}}</td>
                    <td>{{item.celular}}</td>
                    <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                    <td>
                        <a href="{% url 'trabajadores:trabajador_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                        <a href="{% url 'trabajadores:trabajador_delete' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
      {% endif  %} 

    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  //llamada al plugin de jquerys
  $(document).ready(function(){
    $('.table').DataTable()
  })
</script>
{% endblock %}